language: android
jdk: oraclejdk8

android:
  components:
    - android-28
    - build-tools-29.0.2

before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;29.0.2"
script:
  - ./gradlew test build

notifications:
  email: jroquet@arkanosis.net
